spring:
    datasource:
        url: jdbc:mysql://localhost:3306/portfolio_ap
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: false
        show-sql: true
springdoc:
    packages-to-scan: ar.edu.ap.portfolio.controller, ar.edu.ap.portfolio.configuration
    paths-to-match: /v1/**, /api/**
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-docs.html
        operations-sorter: method